### PR TITLE
Attempt at improving the build & release pipelines

### PR DESCRIPTION
**Pull request by lfrancke**
# Description

Attempt at improving the build & release pipelines to use preferred Java versions per Druid version

### CODE REVIEW

**Review by NickLarsenNZ — APPROVED** [review]
LGTM.

Wondered if we want to hard code the available release builds rather than have an input for workflow dispatch?

**Comment by lfrancke** [comment]
Hmm yeah...we could also do that, true.
Let me think about it for a few minutes.

**Comment by lfrancke** [comment]
I tried it. I'm not sure if the syntax is correct or if this is what you had in mind?

**Review by NickLarsenNZ — APPROVED** [review]
LGTM

**Pull request merged**
