### PR TITLE
Adds support for Druid 28.0.1 and updates CI and other dependencies

### PR DESCRIPTION
**Pull request by lfrancke**
# Description

Adds support for Druid 28.0.0 which we'll add in SDP 24.3

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
```

```[tasklist]
# Acceptance
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by sbernauer — COMMENTED** [review]
Change LGTM. Druid 28.0.0 recommends Java 17 (https://druid.apache.org/docs/28.0.0/operations/java/), should we upgrade?

**Comment by lfrancke** [comment]
Good question.
11 is still used on-purpose because this is primarily built for 26.0.0 which [recommends 11](https://druid.apache.org/docs/26.0.0/operations/java/)

For the next version we can make the used JDK, the target and source versions configurable as well but for now I think we can leave it as is.

**Review by sbernauer — APPROVED** [review]
Works for me, this just implies we will stay on Java 11 for 24.3

**Comment by sbernauer** [comment]
Minor Nit: You could bump 28.0.0 -> 28.0.1, although it probably (hopefully?) makes no difference

**Comment by lfrancke** [comment]
I rechecked the dependencies and they are still the same, I updated to 28.0.1

**Review by sbernauer — APPROVED** [review]

**Pull request merged**
